### ISSUE TITLE
websocket连接失败？

### ISSUE THREAD

**Issue by tmxd09887** [jxhczhl/JsRpc#1]
在douyin网页运行
var demo = new Hlclient("ws://127.0.0.1:12080/ws?group=test2&name=test2")
报错
VM38833:16 Refused to connect to 'ws://127.0.0.1:12080/ws?group=test2&name=test2' because it violates the following Content Security Policy directive: "connect-src 'self' *.douyin.com *.snssdk.com *.pstatp.com *.bytednsdoc.com api.feelgood.cn *.bytedance.com *.douyinvod.com *.bytescm.com *.douyincdn.com *.huoshanstatic.com".

api那边提示
注入了ws？没有找到当前组和名字

**Comment by zaimatest** [comment]
> 这不是提示你 connect-src 'self'安全策略问题吗 在我小查了一波资料后，发现通过响应头加的csp防攻击 就是防止websocket注入的吧。不过我刚试了 用fd拦截修改响应头就完事了。看图 ![image](https://user-images.githubusercontent.com/41224971/138560202-76618a2f-cec3-47df-9698-7371b592b9e1.png)

请问下这个是咋操作的，我用Redirect URL, Modify Headers & Mock APIs 扩展工具删不掉这东西

**Comment by zaimatest** [comment]
用Charles搞定了
