### ISSUE TITLE
data:object object

### ISSUE THREAD

**Issue by wubantudl** [jxhczhl/JsRpc#19]
{'data': '[object Object]', 'group': 'test', 'name': 'leigege', 'status': 200}

**Comment by jxhczhl** [comment]
注册的方法中，加个JSON.stringify

**Comment by wubantudl** [comment]
var demo = new Hlclient("ws://127.0.0.1:12080/ws?group=test&name=leigege");
demo.regAction("sign_t", function (resolve, param) {
	t = Date.parse(new Date());
    var list = {
        "page": window.page,
        "sign": window.sign(window.page + '|' + t.toString()),
        "t": t,
	}
	resolve(JSON.stringify(list))
})

谢谢大哥
