### ISSUE TITLE
高频请求会崩溃

### ISSUE THREAD

**Issue by 3642214** [jxhczhl/JsRpc#35]
![image](https://github.com/user-attachments/assets/53d0ea62-72fd-47e4-98e8-6d6c9c47e2e4)
高频率请求会导致崩溃，1.07版本没这问题。

**Comment by jxhczhl** [comment]
可以让我复现一下吗
我调试一下看看

**Comment by jxhczhl** [comment]
已更新~
请再试一下最新版
