### ISSUE TITLE
js代码兼容问题

### ISSUE THREAD

**Issue by sv3nbeast** [jxhczhl/JsRpc#4]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/55974091/164964669-fb0b4d1b-e8cc-4a46-aa28-e635fd4f12fa.png">

复制jsenv.js在目标网站控制台运行后报上图

让把这里的this改成let。请问这里是否存js兼容或者语法问题
```
function Hlclient(wsURL) {
    this.wsURL = wsURL;
    this.handlers = {};
    this.socket = {};

    if (!wsURL) {
        throw new Error('wsURL can not be empty!!')
    }
    this.connect()
}
```

**Comment by jxhczhl** [comment]
提示这个是因为你在断点调试中。你开浏览器的时候就可以先把jsenv.js注入好的，或者你把局部函数暴露给全局再注册。

**Comment by sv3nbeast** [comment]
我尝试先注入jsenv，没有问题，但是下了断点后再去调用没办法调用，请问这个有办法实现运行到断点处获得参数的值、调用其他函数的功能吗，因为一些加密js到运行了才正常使用，想直接在断点处进行改值，调函数，进行远程交互，抱歉哈，因为js不是很熟练，大概意思是这样。

**Comment by jxhczhl** [comment]
你声明一个window全局变量，列如"window.test=其他局部函数" 这样就相当于暴露给全局了，然后你放开断点，后面调用test函数就行了。

**Comment by sv3nbeast** [comment]
学到了，感谢指导和提供的工具
