### ISSUE TITLE
网页ws已返回数据 server端已接收到数据但是并不返回

### ISSUE THREAD

**Issue by WindFgg** [jxhczhl/JsRpc#7]
如标题所示 我本地开了server 经常性看到server端有js端的返回值 但是请求却没有响应

**Comment by lonelyPoker** [comment]
你所使用的server是release中的还是老版本的。若是老版本的请更换成release中的server

**Comment by WindFgg** [comment]
还发现一个新问题 传的参数和返回的参数不一样 我明明穿的是1  但是并发的情况下返回的不是同一个参数

**Comment by jxhczhl** [comment]
好兄弟你倒是上传点图啊，使用场景啊，代码什么的啊

**Comment by WindFgg** [comment]
不是我给不了图 没办法给图 我rpc服务端被我放在了liunx服务器上 我安卓模拟器里面app开的webviewdebug 走的代理 代理是我自己写的一个代理重写数据软件 我也在wifi把rpcserver域名ip排除掉了 但是实测并不是我代理的问题 是他rpcserver开久了 会巨慢 而且在客户端也就是安卓weiview里面注入的rpc环境 ws经常断链

**Comment by lonelyPoker** [comment]
> 没有办法给我的服务器端给我的服务器端应用程序打开的webviewde是我的代理服务器端rpcserver 客户端删除了但是实测了我的 rpc 环境的问题是他开了久了会很慢而且在也就是安卓weiview里面有代理的 rpc 环境 ws 经常断链

JsRpc前端在很复杂的网络环境下出现断连问题，我这边的生产环境下也有过类似的情况，例如:有VPN的网络环境下WebSocket连接状态很不稳定，引发异常服务问题。这个得抽出空余时间去优化

**Comment by WindFgg** [comment]
> 

我已经叫会go的朋友帮忙改好了 https://github.com/jxhczhl/JsRpc

**Comment by lonelyPoker** [comment]
![f59808f21f20cd59fa71395be20ff80](https://user-images.githubusercontent.com/37132457/174037281-17a96a74-35a0-484c-a4a3-8764be29d320.png)
该fork仓库存在WebSocket并发问题

**Comment by mzzsfy** [comment]
重写了一遍 自测吞吐量可以超过4k/秒
https://github.com/mzzsfy/jsRpcServer

**Comment by sihan-bit** [comment]
https://github.com/gin-gonic/gin/issues/2279
